[package]
name = "bote"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "circular"
path = "src/circular.rs"

[dependencies]
rand = "0.8.4"
